package com.young.notepad.web.constants;

/**
 * redis key
 */
public interface RedisKeyConstant {
    // offers look offer list key
    String OFFERS_LOOK_OFFER_LIST = "OFFERS_LOOK_OFFER_LIST";
    // OFFERS_LOOK_ADVERTISER_LIST
    String OFFERS_LOOK_ADVERTISER_LIST = "OFFERS_LOOK_ADVERTISER_LIST";
    // OFFERS_LOOK_AFFILIATE_LIST
    String OFFERS_LOOK_AFFILIATE_LIST = "OFFERS_LOOK_AFFILIATE_LIST";
    // OFFERS_LOOK_ADVERTISER_MANAGER_LIST
    String OFFERS_LOOK_ADVERTISER_MANAGER_LIST = "OFFERS_LOOK_ADVERTISER_MANAGER_LIST";
    // OFFERS_LOOK_AFFILIATE_MANAGER_LIST
    String OFFERS_LOOK_AFFILIATE_MANAGER_LIST = "OFFERS_LOOK_AFFILIATE_MANAGER_LIST";
}
